sed -i 's/S\./M./g' "$1/english.html"
sed -i 's/P\./S./g' "$1/english.html"
sed -i 's/V\./℣./g' "$1/latin.html"
sed -i 's/V\./℣./g' "$1/english.html"
sed -i 's/R\./℟./g' "$1/latin.html"
sed -i 's/R\./℟./g' "$1/english.html"
sed -i 's/S\./<br><span class="red">S.<\/span>/g' "$1/latin.html"
sed -i 's/S\./<br><span class="red">S.<\/span>/g' "$1/english.html"
sed -i 's/M\./<br><span class="red">M.<\/span>/g' "$1/latin.html"
sed -i 's/M\./<br><span class="red">M.<\/span>/g' "$1/english.html"
sed -i 's/℣\./<br><span class="red">℣.<\/span>/g' "$1/latin.html"
sed -i 's/℣\./<br><span class="red">℣.<\/span>/g' "$1/english.html"
sed -i 's/℟\./<br><span class="red">℟.<\/span>/g' "$1/latin.html"
sed -i 's/℟\./<br><span class="red">℟.<\/span>/g' "$1/english.html"
