# Generated by Django 4.1 on 2022-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churches',
            name='mass_types',
        ),
        migrations.AddField(
            model_name='churches',
            name='high_mass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churches',
            name='low_mass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churches',
            name='sung_mass',
            field=models.BooleanField(default=False),
        ),
    ]
