# Generated by Django 4.1 on 2022-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder', '0003_churches_address_churches_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churches',
            name='gmap',
            field=models.CharField(default='', max_length=255),
        ),
    ]
