# Generated by Django 4.1 on 2022-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder', '0004_churches_gmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churches',
            name='gmap',
            field=models.TextField(default=''),
        ),
    ]
