# Generated by Django 4.1 on 2022-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder', '0005_alter_churches_gmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='churches',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
