# Generated by Django 4.1 on 2022-08-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder', '0006_churches_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churches',
            name='count',
        ),
    ]
